; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir = include
src_dir = src

[env]
platform = ststm32
framework = arduino
upload_protocol = custom
extra_scripts = dfu_upload.py
lib_extra_dirs = 
	libraries
build_unflags = 
	-std=c++11
	-std=gnu++11
build_flags = 
	-O2
	-std=c++17
	-std=gnu++17
	-I include
	-Uunix
	-U__unix
	-U__unix__
	-Ulinux
	-U__APPLE__
	-U__OpenBSD__

[env:giga_r1_m7]
board = giga_r1_m7
build_src_filter = 
	-<**>
	+<core_m7/>
lib_deps = 
	arduino-libraries/ArduinoMqttClient@^0.1.8
	alexandros-charitonidis/MiniMessenger@^1.0.0
	
[env:giga_r1_m4]
board = giga_r1_m4
build_src_filter = 
	-<**>
	+<core_m4/>
lib_deps =
	arduino-libraries/Madgwick@^1.2.0
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
	kkloesener/MFRC522_I2C@^1.0
	file://libraries/QTRSensors

[env:giga_r1_m4_rfid_demo]
board = giga_r1_m4
build_src_filter =
	-<**>
	+<rfid_demo/>
lib_deps =
	kkloesener/MFRC522_I2C@^1.0
