[platformio]
include_dir = include
src_dir = src

[env]
platform = ststm32
framework = arduino
upload_protocol = custom
extra_scripts = dfu_upload.py
lib_extra_dirs =
    libraries
build_unflags =
    -std=c++11
    -std=gnu++11
build_flags =
    -O2
    -std=c++17
    -std=gnu++17
    -I include
    -Uunix
    -U__unix
    -U__unix__
    -Ulinux
    -U__APPLE__
    -U__OpenBSD__

[env:giga_r1_m7]
board = giga_r1_m7
build_src_filter =
    -<**>
    +<core_m7/>
lib_deps =
    arduino-libraries/ArduinoMqttClient@^0.1.8
    alexandros-charitonidis/MiniMessenger@^1.0.0
    kkloesener/MFRC522_I2C@^1.0
    martinsos/HCSR04@^2.0.0
    file://libraries/QTRSensors

[env:giga_r1_m4]
board = giga_r1_m4
build_src_filter =
    -<**>
    +<core_m4/>
